# Generated by Django 6.0.4 on 2026-04-21 22:26

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InquiryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('thank_you_text', wagtail.fields.RichTextField(blank=True)),
                ('email_to', models.EmailField(blank=True, help_text='Where inquiry notifications should be sent.', max_length=254)),
                ('email_from', models.EmailField(blank=True, help_text='Optional from address for notification emails.', max_length=254)),
                ('email_subject', models.CharField(blank=True, default='New website inquiry', max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
