# Generated by Django 6.0.4 on 2026-05-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirypage',
            name='captcha_label',
            field=models.CharField(blank=True, default='Captcha', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='email_label',
            field=models.CharField(blank=True, default='Email address', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='email_placeholder',
            field=models.CharField(blank=True, default='you@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Contact us', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='message_label',
            field=models.CharField(blank=True, default='How can we help?', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='message_placeholder',
            field=models.CharField(blank=True, default='Tell us how we can help.', max_length=255),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='name_label',
            field=models.CharField(blank=True, default='Full name', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='name_placeholder',
            field=models.CharField(blank=True, default='Your full name', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='phone_label',
            field=models.CharField(blank=True, default='Phone number', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='phone_placeholder',
            field=models.CharField(blank=True, default='555-555-5555', max_length=100),
        ),
        migrations.AddField(
            model_name='inquirypage',
            name='submit_button_text',
            field=models.CharField(blank=True, default='Send Inquiry', max_length=100),
        ),
    ]
