# Generated by Django 6.0.4 on 2026-05-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0003_inquirypage_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquirypage',
            name='hero_image_alt',
            field=models.CharField(blank=True, help_text='Describe the image for accessibility and SEO.', max_length=255),
        ),
    ]
