# Generated by Django 6.0.4 on 2026-05-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='wechat_id',
            field=models.CharField(blank=True, help_text='WeChat ID or contact handle', max_length=100),
        ),
    ]
