# Generated by Django 6.0.4 on 2026-05-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicepage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='back_to_services_text',
            field=models.CharField(blank=True, default='← Back to Services', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Service', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='pricing_note_heading',
            field=models.CharField(blank=True, default='Pricing note', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sidebar_button_text',
            field=models.CharField(blank=True, default='Send an Inquiry', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sidebar_heading',
            field=models.CharField(blank=True, default='Need help?', max_length=100),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='sidebar_text',
            field=models.CharField(blank=True, default='Send us an inquiry and we’ll respond with the next steps.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='empty_services_text',
            field=models.CharField(blank=True, default='No services available yet.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Services', max_length=100),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='service_card_text',
            field=models.CharField(blank=True, default='Learn more about this service and how we can help.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='services_heading',
            field=models.CharField(blank=True, default='Immigration Services', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='services_intro',
            field=models.CharField(blank=True, default='Explore our available service areas and choose the option that best fits your needs.', max_length=255),
        ),
        migrations.AddField(
            model_name='servicesindexpage',
            name='view_service_text',
            field=models.CharField(blank=True, default='View service →', max_length=100),
        ),
    ]
