# Generated by Django 6.0.4 on 2026-05-10 22:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


def populate_translation_keys(apps, schema_editor):
    StudyWorkProgramCard = apps.get_model("studywork", "StudyWorkProgramCard")

    for card in StudyWorkProgramCard.objects.all():
        card.translation_key = uuid.uuid4()
        card.save(update_fields=["translation_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("studywork", "0001_initial"),
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studyworkprogramcard",
            options={},
        ),
        migrations.AddField(
            model_name="studyworkprogramcard",
            name="locale",
            field=models.ForeignKey(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailcore.locale",
                verbose_name="locale",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studyworkprogramcard",
            name="translation_key",
            field=models.UUIDField(
                editable=False,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_translation_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="studyworkprogramcard",
            name="translation_key",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studyworkprogramcard",
            unique_together={("translation_key", "locale")},
        ),
    ]
