# Generated by Django 6.0.4 on 2026-05-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studywork', '0002_alter_studyworkprogramcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyworkprogramcard',
            name='body_text',
            field=models.TextField(blank=True, help_text='Use plain text. Line breaks and bullet characters will be preserved on the page. This field is easier to translate as one block.'),
        ),
    ]
