# Generated by Django 6.0.4 on 2026-05-12 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studywork', '0003_studyworkprogramcard_body_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyworkprogramcard',
            name='body',
        ),
    ]
