# Generated by Django 6.0.4 on 2026-05-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='article_label',
            field=models.CharField(blank=True, default='Article', max_length=100),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='empty_posts_text',
            field=models.CharField(blank=True, default='No blog posts yet.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='hero_eyebrow',
            field=models.CharField(blank=True, default='Blog', max_length=100),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='post_card_text',
            field=models.CharField(blank=True, default='Read more about this topic and how it may apply to your situation.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='posts_heading',
            field=models.CharField(blank=True, default='Latest Posts', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='posts_intro',
            field=models.CharField(blank=True, default='Read helpful updates, guidance, and information.', max_length=255),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='read_post_text',
            field=models.CharField(blank=True, default='Read post →', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='article_label',
            field=models.CharField(blank=True, default='Article', max_length=100),
        ),
        migrations.AddField(
            model_name='blogpage',
            name='back_to_blog_text',
            field=models.CharField(blank=True, default='← Back to Blog', max_length=100),
        ),
    ]
