# Generated by Django 6.0.4 on 2026-05-09 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_hero_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='rss_feed_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rss_heading',
            field=models.CharField(blank=True, default='Immigration headlines', max_length=120),
        ),
        migrations.AddField(
            model_name='homepage',
            name='rss_item_count',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='homepage',
            name='show_rss_feed',
            field=models.BooleanField(default=True),
        ),
    ]
