# Generated by Django 6.0.4 on 2026-05-18 11:24

import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('eyebrow', models.CharField(blank=True, default='Why Us', max_length=100)),
                ('intro', wagtail.fields.RichTextField(blank=True)),
                ('main_image_alt', models.CharField(blank=True, help_text='Describe the image for accessibility and SEO.', max_length=255)),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='WhyUsReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_key', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('subtitle', models.CharField(max_length=255)),
                ('details_text', models.TextField(blank=True, help_text='Use plain text. For paragraph breaks, use [[p]]. For simple line breaks, use [[br]].')),
                ('bullet_items', models.TextField(blank=True, help_text='Enter one bullet item per line. For Wagtail Localize, you may also use [[br]] between bullet items.')),
                ('open_by_default', models.BooleanField(default=False, help_text='If selected, this section will be expanded when the page first loads.')),
                ('locale', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.locale', verbose_name='locale')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='reasons', to='whyus.whyuspage')),
            ],
            options={
                'abstract': False,
                'unique_together': {('translation_key', 'locale')},
            },
        ),
    ]
