# Generated by Django 6.0.4 on 2026-05-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('whyus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whyusreason',
            options={'ordering': ['sort_order']},
        ),
        migrations.AlterUniqueTogether(
            name='whyusreason',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='whyusreason',
            constraint=models.UniqueConstraint(fields=('translation_key', 'locale'), name='unique_translation_key_locale_whyus_whyusreason'),
        ),
    ]
