# Generated by Django 6.0.4 on 2026-05-17 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_aboutpage_certificate_1_aboutpage_certificate_2_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='about_video_file',
            field=models.FileField(blank=True, help_text='Upload an MP4 video file for the About page.', upload_to='about/videos/'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='about_video_poster',
            field=models.ForeignKey(blank=True, help_text='Poster image shown before the About page video plays.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
