# Generated by Django 6.0.4 on 2026-05-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutpage_about_video_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='eyebrow',
            field=models.CharField(blank=True, default='About', max_length=100),
        ),
    ]
